// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_500.tsx";
import * as $3 from "./routes/_middleware.ts";
import * as $4 from "./routes/about/contact.tsx";
import * as $5 from "./routes/about/index.tsx";
import * as $6 from "./routes/api/joke.ts";
import * as $7 from "./routes/api/random-uuid.ts";
import * as $8 from "./routes/countdown.tsx";
import * as $9 from "./routes/github/[username].tsx";
import * as $10 from "./routes/greet/[name].tsx";
import * as $11 from "./routes/html.tsx";
import * as $12 from "./routes/index.tsx";
import * as $13 from "./routes/myHandler.ts";
import * as $14 from "./routes/plain.tsx";
import * as $15 from "./routes/search.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";
import * as $$2 from "./islands/MyIsland.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_500.tsx": $2,
    "./routes/_middleware.ts": $3,
    "./routes/about/contact.tsx": $4,
    "./routes/about/index.tsx": $5,
    "./routes/api/joke.ts": $6,
    "./routes/api/random-uuid.ts": $7,
    "./routes/countdown.tsx": $8,
    "./routes/github/[username].tsx": $9,
    "./routes/greet/[name].tsx": $10,
    "./routes/html.tsx": $11,
    "./routes/index.tsx": $12,
    "./routes/myHandler.ts": $13,
    "./routes/plain.tsx": $14,
    "./routes/search.tsx": $15,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
    "./islands/MyIsland.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
